[workspace]
name = "pirna_ppi"
description = "piRNA PPI"
version = "0.1.0"
channels = ['conda-forge']
platforms = ['linux-64']

[dependencies]
python = "~=3.10.0"
loguru = "*"
ruff = "*"
tqdm = "*"
typer = "*"
pip = "*"
biopython = ">=1.86,<2"
ipykernel = ">=7.1.0,<8"

[pypi-dependencies]
mkdocs = "*"
python-dotenv = "*"
pirna_ppi = { path = ".", editable = true }
