[workspace]
name = "pirna_ppi"
description = "piRNA PPI"
version = "0.1.0"
channels = ['conda-forge', "bioconda"]
platforms = ['linux-64']

[dependencies]
python = "~=3.10.0"
loguru = "*"
ruff = "*"
tqdm = "*"
typer = "*"
pip = "*"
ipykernel = ">=7.1.0,<8"
mmseqs2 = ">=18.8cc5c,<19"
hmmer = ">=3.4,<4"
aria2 = ">=1.37.0,<2"

[pypi-dependencies]
mkdocs = "*"
python-dotenv = "*"
pirna_ppi = { path = ".", editable = true }
colabfold = { git = "https://github.com/sokrypton/ColabFold" }
biopython = "<1.86"
